#!/bin/bash

# GTK-reSlider made by BuriXon-code (c) 2025

RED_BOLD='\033[1;31m'
RED='\033[0;31m'
YELLOW_BOLD='\033[1;33m'
YELLOW="\033[0;33m"
GREEN='\033[0;32m'
GREEN_BOLD='\033[1;32m'
NC='\033[0m'

GTK_DIR="$HOME/.config/gtk-3.0"
GTK_FILE="$GTK_DIR/gtk.css"

new() {
	if [ ! -d "$GTK_DIR" ]; then
		mkdir -p "$GTK_DIR"
	fi
	echo -e "scrollbar slider {\n\tmin-width: ${set_size}px;\n\tmin-height: ${set_size}px;\n}" > "$GTK_FILE"
	if [ ! -f "$GTK_DIR/gtk-dark.css" ]; then
		ln -s "$GTK_FILE" "$GTK_DIR/gtk-dark.css"
	fi
	echo -e "${GREEN}Generated a new scrollbar style: ${GREEN_BOLD}${set_size}px${NC}\n"
}

edit() {
	temp_file=$(mktemp)
	awk -v size="$set_size" '
		BEGIN { inside_block = 0 }
		/^\s*scrollbar slider\s*\{/ {
			inside_block = 1
			print "scrollbar slider {"
			print "\tmin-width: " size "px;"
			print "\tmin-height: " size "px;"
			next
		}
		/^\s*\}/ && inside_block {
			inside_block = 0
			print "}"
			next
		}
		{
			if (!inside_block) print $0
		}
	' "$GTK_FILE" > "$temp_file"
	mv "$temp_file" "$GTK_FILE"
	echo -e "${GREEN}Edited the scrollbar width and height: ${GREEN_BOLD}${set_size}px${NC}\n"
}

if [ -z "$1" ]; then
	echo -e "\n${RED_BOLD}Error:${NC} ${RED}Provide a number as a parameter!${NC}\n"
	exit 1
fi

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
	echo -e "\n${RED_BOLD}Error:${NC} ${RED}The provided parameter must be an integer!${NC}\n"
	exit 1
fi

number=$1

if [ "$number" -le 5 ]; then
	echo -e "\n${YELLOW}Are you crazy, user?\nYou won't even notice ${number}px...\nAre you sure you want to set this value? [${YELLOW_BOLD}Y/N${YELLOW}]${NC}"
	read answer
	if [[ "$answer" =~ ^[Yy]$ ]]; then
		set_size=$number
	else
		echo -e "\n${RED_BOLD}Cancelled:${NC} ${RED}Operation aborted.${NC}\n"
		exit 1
	fi
elif [ "$number" -ge 30 ]; then
	echo -e "\n${YELLOW}User, don't overdo it!\nA scrollbar half the screen size isn't good either.\nAre you sure you want to set this value? [${YELLOW_BOLD}Y/N${YELLOW}]${NC}"
	read answer
	if [[ "$answer" =~ ^[Yy]$ ]]; then
		set_size=$number
	else
		echo -e "\n${RED_BOLD}Cancelled:${NC} ${RED}Operation aborted.${NC}\n"
		exit 1
	fi
else
	set_size=$number
fi

if [ ! -f "$GTK_FILE" ]; then
	echo -e "\n${YELLOW}Creating a new style file.${NC}"
	new
elif [ ! -s "$GTK_FILE" ]; then
	echo -e "\n${YELLOW}The file is empty. Adding a new style.${NC}"
	new
else
	if grep -q "scrollbar slider" "$GTK_FILE"; then
		echo -e "\n${YELLOW}Editing the existing scrollbar style.${NC}"
		edit
	else
		echo -e "\n${YELLOW}Adding a new style to the existing file.${NC}"
		new
	fi
fi
